### ISSUE TITLE
Can only have one delegate?

### ISSUE THREAD

**Issue by nitrag** [igroomgrim/CLLocationManager-Singleton-in-Swift#1]
I have setup your singleton and have it working in my main view controller (mapview). I have a secondary view controller which records the GPS tracks into a line. However, this second view controller doesn't receive the delegate callbacks.

1. Setup Singleton (working)
2. Implement 1st delegate in Main VC (working)
3. Implement 2nd delegate in Secondary VC (not working)

Can you test on your end please?

**Comment by igroomgrim** [comment]
Thanks for notice me. You can change to setup delegate property on `viewWillAppear` and release it on `viewWillDisappear`, then you delegate method will work on every view controller 

exmaple : 
`
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        LocationService.sharedInstance.delegate = self
    }
`    

`
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        LocationService.sharedInstance.delegate = nil
    }`

**Comment by nitrag** [comment]
I have two view controllers in view at the same time (UI View Container),
so this won't necessarily work. I was reading on Stack Overflow that
NSNotificationCenter or an Observer pattern should be used. I'm new to
swift otherwise I'd make a PR.

I have a work around in the meantime but I'm not sure if it will last as my
app gets more complicated.

Thanks for the quick reply.

**Comment by igroomgrim** [comment]
Oh sorry for inconvenience. You can use Observer pattern instead Singleton.
This project i use singleton because ensures that only one instance exists for a given class.
 Also you can read more information on this [Introducing Design Patterns in Swift](https://www.raywenderlich.com/86477/introducing-ios-design-patterns-in-swift-part-1) that link will give more information for you. 

GGHF : Good luck have fun 💃
